#!/usr/bin/env bash
# Transfer a file from client to server using scp

# Check if correct number of arguments is provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables for readability
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Use scp to transfer the file to the server
scp -i "$ssh_key_path" -o StrictHostKeyChecking=no "$file_path" "$username@$server_ip":~/

# Check if scp command was successful
if [ "$?" -eq 0 ]; then
    echo "File transferred successfully to $username@$server_ip:~/"
else
    echo "Error: File transfer failed"
fi
