#!/usr/bin/env bash
# This script contains answers to questions related to MAC and IP addresses.

# Question 1: What is a MAC address?
# Answer: The unique identifier of a network interface.
2

# Question 2: What is an IP address?
# Answer: Is to devices connected to a network what postal address is to houses.
1
