#!/usr/bin/env bash
# This script contains answers to questions related to UDP and TCP.

# Question 1: Which statement is correct for the TCP box?
# Answer: It is a protocol that is transferring data in a slow way but surely.
1

# Question 2: Which statement is correct for the UDP box?
# Answer: It is a protocol that is transferring data in a fast way and might lose data along in the process.
2

# Question 3: Which statement is correct for the TCP worker?
# Answer: Have you received boxes x, y, z?
1
