#!/usr/bin/env bash
# Script Name: 100-process_and_pid_file
# Description: Displays "To infinity and beyond" indefinitely
#              Displays "I hate the kill command" when receiving a SIGTERM signal
#              Displays "Y U no love me?!" when receiving a SIGINT signal
#              Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

pidfile="/var/run/myscript.pid"

trap 'echo "I hate the kill command"; exit 0' SIGTERM
trap 'echo "Y U no love me?!"; exit 0' SIGINT
trap 'rm -f "$pidfile"; exit 0' SIGQUIT

echo "$$" > "$pidfile"

while true; do
    echo "To infinity and beyond"
    sleep 2
done
