#!/usr/bin/env bash
# Script Name: 101-manage_my_process
# Description: Bash (init) script for managing the process in 100-process_and_pid_file

pidfile="/var/run/myscript.pid"
script="./100-process_and_pid_file"

start() {
    if [ -f "$pidfile" ]; then
        echo "manage_my_process is already started"
    else
        "$script" &
        echo "$!" > "$pidfile"
        echo "manage_my_process started"
    fi
}

stop() {
    if [ -f "$pidfile" ]; then
        pid=$(cat "$pidfile")
        rm -f "$pidfile"
        kill "$pid"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case $1 in
    start) start;;
    stop) stop;;
    restart) restart;;
    *) echo "Usage: $0 {start|stop|restart}"; exit 1;;
esac
