#!/usr/bin/env bash
# Script Name: 4-to_infinity_and_beyond
# Description: Displays "To infinity and beyond" indefinitely with a
# sleep of 2 seconds between iterations

while true
do
    echo "To infinity and beyond"
    sleep 2
done
