#!/usr/bin/env bash
# Script Name: 6-stop_me_if_you_can
# Description: Stops the 4-to_infinity_and_beyond process without using kill or killall

pid=$(pgrep -fo "4-to_infinity_and_beyond")
if [ -n "$pid" ]; then
    echo "Stopping process: $pid"
    kill "$pid"
else
    echo "Process not found"
fi
