#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays the data using awk

awk '{ip_status[$1 " " $9]++} END {for (key in ip_status) print ip_status[key], key}' apache-access.log | sort -nr
