#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

hour=0

while [ "$hour" -lt 12 ]; do
    echo "Hour: $hour"
    
    for ((min=1; min<=59; min++)); do
        echo "$min"
    done

    ((hour++))
done
