#!/usr/bin/env bash
# This script changes the IP address of localhost and facebook.com.

# Change localhost IP to 127.0.0.2
sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts

# Change facebook.com IP to 8.8.8.8
sudo sed -i 's/157.240.11.35/8.8.8.8/' /etc/hosts
