#!/usr/bin/env bash
# This script changes the IP address of localhost and facebook.com.

temp_hosts="/tmp/hosts.new"

cp /etc/hosts "$temp_hosts"
echo "127.0.0.2       localhost" > "$temp_hosts"
echo "8.8.8.8        facebook.com" >> "$temp_hosts"
sudo cp -f "$temp_hosts" /etc/hosts

# Clean up temporary file
rm "$temp_hosts"
